/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import controller.ControllerServer;
import domen.Prodavac;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import niti.NitPokreniServer;
import niti.RefreshThread;

/**
 *
 * @author Sandra
 */
public class ServerForma extends javax.swing.JFrame {
private NitPokreniServer pokreniServer;
    /**
     * Creates new form ServerForma
     */
    public ServerForma() {
        initComponents();
        setLocationRelativeTo(null);
        srediFormu();
        try {
        //tabela
        
        fillTable();
    } catch (Exception ex) {
        Logger.getLogger(ServerForma.class.getName()).log(Level.SEVERE, null, ex);
    }
       
          
        //refresh
        RefreshThread rt = new RefreshThread(this);
        rt.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblServer = new javax.swing.JLabel();
        btnPokreni = new javax.swing.JButton();
        btnZaustavi = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCurrentUsers1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SERVER");
        setResizable(false);

        lblServer.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblServer.setText("jLabel1");

        btnPokreni.setText("Pokreni");
        btnPokreni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPokreniActionPerformed(evt);
            }
        });

        btnZaustavi.setText("Zaustavi");
        btnZaustavi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZaustaviActionPerformed(evt);
            }
        });

        tblCurrentUsers1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Korisnicko ime"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCurrentUsers1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblCurrentUsers1PropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(tblCurrentUsers1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnPokreni, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnZaustavi, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblServer, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblServer, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPokreni, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZaustavi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPokreniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPokreniActionPerformed
       pokreniServer=new NitPokreniServer();
       pokreniServer.start();
       lblServer.setText("Server je pokrenut!");
       btnPokreni.setEnabled(false);
       btnZaustavi.setEnabled(true);
    }//GEN-LAST:event_btnPokreniActionPerformed

    private void btnZaustaviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZaustaviActionPerformed
        int odgovor = JOptionPane.showConfirmDialog(this, "Zalite da iskljucite server?", "Server", JOptionPane.YES_NO_OPTION);
        if (odgovor == JOptionPane.YES_OPTION) {
            pokreniServer.interrupt();
            JOptionPane.showMessageDialog(this, "Server je iskljucen.");
            this.dispose();
            System.exit(0);
        }
    }//GEN-LAST:event_btnZaustaviActionPerformed

    private void tblCurrentUsers1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblCurrentUsers1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tblCurrentUsers1PropertyChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPokreni;
    private javax.swing.JButton btnZaustavi;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblServer;
    private javax.swing.JTable tblCurrentUsers1;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
     lblServer.setText("Server nije pokrenut.");
     btnZaustavi.setEnabled(false);
     btnPokreni.setEnabled(true);
    }
    private void fillTable() throws Exception {
        
          List<Prodavac> list = ControllerServer.getInstance().getListaUlogovani();

       tblCurrentUsers1.setModel(new TableModelServer(list));
         }

    

    public void refresh() throws Exception {
        fillTable();
    }
}
